### PR TITLE
Added Isilon driver

### PR DESCRIPTION
**Pull request by clintonskitson**
This commit introduces the basic volume managemnet functionality
for Isilon. Snapshots are not included.

### CODE REVIEW

**Comment by clintonskitson** [comment]
@akutz Going to need your eyes on this one. I am no RC2 and am not getting local devices coming through on the context. Also it looks like the instance isn't being cached. Not sure how this would differ from other drivers in this respect, so might step back to RC1 to test. 

There is also an update to make sure the size is not a required field as it shouldn't be for NAS devices. I am not sure where to properly make that change.

**Comment by clintonskitson** [comment]
@akutz This looks to be in order! 

cc @oskoss

**Comment by akutz** [comment]
Hi @clintonskitson,

I've updated the [tip of my isilon branch](https://github.com/akutz/libstorage/commit/297a02bf48610b21ef744b41efbcff3fce3ca941) that's rebased onto master to account for recent changes to master. Please feel free to reset your PR's branch to the tip of mine.

**Comment by akutz** [comment]
Hi @oskoss, @mux23, 

Do either of you have access to an Isilon setup you've used to previously test REX-Ray that I could use to test this PR? We're trying to get a release ready, and testing is moving too slowly. I'd like to help @clintonskitson by taking over some of that where I'm able. I'd appreciate any assistance either of you might be able to provide. Thank you!

**Comment by mux23** [comment]
hey @akutz - I definitely do not, the only environments I have any access to are AWS and GCE - but let me ping someone and see if I can find more information for you.

**Comment by akutz** [comment]
Hi @clintonskitson,

The libStorage 0.1.0 milestone will be delayed until 2016/05/17 to accommodate testing this driver. 

It's 6:41PM CST here, and too late to cut an RC for testing today as this driver's validation is blocking libStorage 0.1.0-RC3.

By end-of-day Monday, 2016/05/16, we should plan to have the Isilon driver tested and ready for inclusion in libStorage 0.1.0 RC3. Tuesday, 2016/05/17 can then be used to validated RC3, and once validated, RC3 can be tagged and released as libStorage 0.1.0.

Dates are subject to change depending on the duration and results of the tests, as well as whether or not @mux23 is able to find some Isilon environment in which others in addition to @clintonskitson can assist with testing and validation of the driver.

**Comment by clintonskitson** [comment]
@akutz I did a PR to your branch.

https://github.com/akutz/libstorage/pull/1

**Comment by akutz** [comment]
Hi @clintonskitson,

Is there a reason you didn't reset the PR's existing branch to the tip of mine and then apply your changes? I'm happy to handle it the other way, but it won't close this PR, and I prefer to maintain an issue's provenance when possible.

**Comment by clintonskitson** [comment]
I wasn't sure that I was doing the right thing. I will do that now.

**Comment by akutz** [comment]
Hi @clintonskitson,

Sure thing, I understand. Here is an example of what you could do:

### Back-up your Isilon branch
```
$ git branch feature/isilon.bak feature/isilon
```

### Add my repo as a remote / Fetch its contents
```
$ KUTZ_REMOTE=$(git remote -v | grep akutz | head -n 1 | awk '{print $1}'); \
  if [ -z "$KUTZ_REMOTE" ]; \
  then git remote add kutz "https://github.com/akutz/libstorage.git"; git fetch -v kutz; \
  else git fetch -v $KUTZ_REMOTE; \
  fi
```

### Checkout your Isilon branch
```
$ git checkout feature/isilon
```

### Reset your Isilon branch to tip of my Isilon branch
```
$ git reset --hard $(git remote -v | grep akutz | head -n 1 | awk '{print $1}')/feature/isilon
```

### Cherry-pick commit from the PR you created for my Isilon branch into your Isilon branch
```
$ git cherry-pick 50d23546c730a2b76be1988ed5f53ca25c56e6ee
```

### Force push your Isilon branch to your repo
```
$ git push --force $(git remote -v | grep clintonskitson | head -n 1 | awk '{print $1}')
```

That should result in the PR branch being updated, as well as forcing a new Travis build.

**Comment by clintonskitson** [comment]
Done deal.

**Pull request merged**
