### PR TITLE
Updated log message on libs directory create

### PR DESCRIPTION
**Pull request by clintonskitson**
This changes the log message from info to debug when the
libstorage directory is created.

### CODE REVIEW

**Comment by akutz** [comment]
So that happens just once, the first time it occurs, and only if the directory doesn't exist. I like it at info so we know what directories the app is using. In testing we'll see it a lot due to rotating test dirs, so maybe it's more annoying in test than it would be in prod?

**Comment by clintonskitson** [comment]
Was doing it with each CLI command from RR.

**Comment by clintonskitson** [comment]
Here is the message `INFO[0000] making libStorage directory                   mustPerm=false path= perms=-rwxr-xr-x`.

**Comment by akutz** [comment]
Hi @clintonskitson,

I'm closing this because it was handled elsewhere.

**Pull request closed without merging**
