### PR TITLE
Added ability to query volumes by service

### PR DESCRIPTION
**Pull request by clintonskitson**
This commit introduces the ability to query for all volumes from
a given service name.

### CODE REVIEW

**Comment by clintonskitson** [comment]
@akutz Not sure if this is valid naming of the method.

**Comment by akutz** [comment]
Hi @clintonskitson,

Per the APIB docs I've been following the Swagger convention of {COLLECTION}BY{PIVOT}, hence `VolumesByServce`, but if you don't have time to make the change, I'll happily accept this as is and worry about it later.

**Comment by akutz** [comment]
Hi @clintonskitson,

Could you comment on this change as to whether it's something you're willing to do or wish to keep as is? If you want to keep it, I'll merge this.

**Comment by clintonskitson** [comment]
@akutz This has been rebased and updated.

**Pull request merged**
