### PR TITLE
InstanceID and LocalDevice headers

### PR DESCRIPTION
**Pull request by akutz**
This patch updates the libStorage client so that all outgoing HTTP requests to the storage-related API functions automatically have added to their payloads, as headers, the client's instance ID and local device information.

The instance ID and local device data is read on the server-side and made available to drivers with the context.

### CODE REVIEW

**Comment by clintonskitson** [comment]
https://github.com/emccode/libstorage/blob/39deff8a6b3b1e643e093cbd39bec04c38446725/api/tests/tests.go#L279-L282

This is resulting in the following
```
--- FAIL: TestClient (1.01s)
        Error Trace:    tests.go:206
			tests.go:148
			tests.go:101
			mock_test.go:75
	Error:  	Received unexpected error "error dialing libStorage service"
```

Doing a panic on the error before the return is yielding
```
--- FAIL: TestClient (1.01s)
panic: open /Users/clintonkitson/.libstor/lsx-darwin: no such file or directory [recovered]
	panic: open /Users/clintonkitson/.libstor/lsx-darwin: no such file or directory
```

**Comment by clintonskitson** [comment]
Creating the .libstor directory gets past the error.

**Comment by akutz** [comment]
Ah. Good catch. I auto create the global dirs but do not that one. I'll add that. Thanks!

-- 
-a

**Comment by clintonskitson** [comment]
Hmm.. doesn't look like I am getting the instance ID.

```
ERRO[0001] cannot get attachments without instance ID    host=tcp://127.0.0.1:48247 route=volumesAndAttachments server=polar-crystal-ge tls=false
--- FAIL: TestVolumesWithAttachments (1.14s)
```

**Comment by clintonskitson** [comment]
Also the error details were getting squashed with this one from the goof.Error.

```
--- FAIL: TestClient (1.01s)
        Error Trace:    tests.go:206
            tests.go:148
            tests.go:101
            mock_test.go:75
    Error:      Received unexpected error "error dialing libStorage service"
```

**Comment by akutz** [comment]
I thought I said I want yet sending it automatically. I just get it via the client.

-- 
-a

**Comment by akutz** [comment]
This isn't the logger printing it out, this is the testify assert packages assert.NoError method. I never forked that to unwind the inner error details. The goof error only gets unpacked by the logrus fork or other projects that know how to unpack it,

-- 
-a

**Comment by akutz** [comment]
Hi @clintonskitson,

By the way, thanks to some PRs for Goof (see example in [goof_test.go#11](https://github.com/akutz/goof/blob/master/goof_test.go#L11)), I actually am able to show inner errors even when using Testify's `assert.NoError` validation:

```
time="2016-04-23T18:47:56-05:00" level=info msg="server started" server=love-ant-gm 
--- FAIL: TestClient (1.16s)
        Error Trace:    tests.go:208
			tests.go:150
			tests.go:103
			mock_test.go:75
	Error:  	Received unexpected error "msg=\"error dialing libStorage service\" host=tcp://127.0.0.1:53278 inner=\"error downloading executor\""
		
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x7fe48]
```

**Comment by clintonskitson** [comment]
That's awesome sauce.

**Comment by akutz** [comment]
Hi @clintonskitson,

Codecov, or whomever hosts its bash scripts, is offline for maintenance, but the latest commit works fine locally. The coverage step is what's failing the build, so don't worry about that bit. Anyway, this branch is updated so that the instance ID is now injected into the context on the server side after being automatically set on the client.

The tests [`TestVolumes`](https://github.com/emccode/libstorage/pull/40/files#diff-0c5799aa79247712babf4c3a9dad3141L100) and [`TestVolumesWithAttachments`](https://github.com/emccode/libstorage/pull/40/files#diff-0c5799aa79247712babf4c3a9dad3141R149) prove it out.

On the driver side it should be as simple as using `ctx.InstanceID()`

**Comment by akutz** [comment]
The latest update to this commit also sends across the local devices map:

```
DEBU[0001] getting instance IDs                          host=tcp://127.0.0.1:45597
DEBU[0001] getting local devices                         host=tcp://127.0.0.1:45597
DEBU[0001] created new libStorage client                 host=tcp://127.0.0.1:45597
INFO[0001]                                              
INFO[0001]     -------------------------- HTTP REQUEST (CLIENT) ------------------------- 
INFO[0001]     GET /volumes?attachments=true HTTP/1.1   
INFO[0001]     Host: 127.0.0.1:45597                    
INFO[0001]     Libstorage-Instanceid64: mock=eyJpZCI6IjEyMzQ1IiwibWV0YWRhdGEiOnsibWF4IjoxMCwibWluIjowLCJyYWQiOiJjb29sIiwidG90YWxseSI6InR1YnVsYXIifX0= 
INFO[0001]     Libstorage-Localdevices: mock=/dev/xvda=/var/log, /dev/xvdb=/home, /dev/xvdc=/net/share, /dev/xvdd=/var/lib/backup 
INFO[0001]                                              
DEBU[0001] http request                                  route=volumes
DEBU[0001] added route middleware                         middleware=schema-validator route=volumes
```

**Pull request merged**
