### PR TITLE
ScaleIO Driver Performance Update

### PR DESCRIPTION
**Pull request by vladimirvivien**
## ⚠️ WIP, Depends on https://github.com/emccode/goscaleio/pull/17 Merged ⚠️ 

This set of code changes are designed to improve the scaleIO driver
performance by reducing considerably the number of HTTP API calls made to
the backend storage gateway as outline in the following table.

**Driver Init (no change)**

```
2016/08/18 13:12:21 GET: /api/version
2016/08/18 13:12:21 GET: /api/login
2016/08/18 13:12:21 GET: /api/types/System/instances
2016/08/18 13:12:21 GET: /api/types/ProtectionDomain/instances
2016/08/18 13:12:21 GET: /api/types/StoragePool/instances
```

**Volumes:** 3-to-1 reduction
Previously took 3 calls, now only one

```
2016/08/18 08:51:18 GET: /api/types/Volume/instances
```

**VolumeInspect:** 3-to-1 reduction

```
2016/08/18 09:57:12 GET: /api/instances/Volume::a2b7f37f00000002
```

**VolumeCreate:** 5-to-2

```
2016/08/18 08:49:00 POST: /api/types/Volume/instances
2016/08/18 08:49:00 GET: /api/instances/Volume::a2b7f38200000003
```

**VolumeRemove:**  2-to-1

```
2016/08/18 09:01:21 POST: /api/instances/Volume::a2b7f38200000003/action/removeVolume
```

**VolumeAttach:** 5-to-2 if force=false

```
2016/08/18 12:34:52 POST: /api/instances/Volume::a2b7f37f00000002/action/addMappedSdc
2016/08/18 12:34:52 GET: /api/instances/Volume::a2b7f37f00000002
```

**VolumeAttach:** 12-to-4 if force=true **

```
2016/08/18 13:41:46 GET: /api/instances/Volume::a2b7f37f00000002
2016/08/18 13:41:46 POST: /api/instances/Volume::a2b7f37f00000002/action/removeMappedSdc
2016/08/18 13:41:46 POST: /api/instances/Volume::a2b7f37f00000002/action/addMappedSdc
2016/08/18 13:41:46 GET: /api/instances/Volume::a2b7f37f00000002
```

**VolumeDetach:** 5-to-2

```
2016/08/18 12:47:13 POST: /api/instances/Volume::a2b7f37f00000002/action/removeMappedSdc
2016/08/18 12:47:13 GET: /api/instances/Volume::a2b7f37f00000002
```

### CODE REVIEW

**Comment by vladimirvivien** [comment]
Not sure why build is applying the wrong ref in glide.  The glide file in this PR has the correct ref hash value of `0a0847888970ea577a2b9c96fcd5463dffbf7717`, but the build is trying to download an something else:
```
[ERROR]	Failed to set version on github.com/emccode/goscaleio to 76e031331e2babb894129d8b21dce88922301411: Unable to update checked out version
```
Anyway to force the build to use what's in the glide file ?

**Comment by akutz** [comment]
Hi Vlad,

I'll take a look in a bit. FWIW, we don't really want to merge until GoScaleIO merges from your PR there regardless.

**Comment by akutz** [comment]
Hey, I had an idea. Go to the PR build and clear its cache. I'll take a look myself and rerun the build.

**Comment by akutz** [comment]
Not a cache issue as it's not enabled on the repo. I did notice your lock file is out of date. Please rerun 'glide up' to make sure the lock file is up to date. 'make glide.lock' may also work.

Additionally, dumb question; but since I'm on mobile I'll ask. Did you push the patch to your fork being referenced here? The commit ID in your GoScaleIO fork I mean?

**Comment by vladimirvivien** [comment]
@akutz thanks for taking a look.  Agreed I don't want this merged until the GoScaleIO is merged, then I will update to point to proper ref.  Yes, my patch to goscaleio, referenced in glide,  is pushed (i triple checked that).  But, I will try your couple prescriptions above to see what happens.  Thanks!!

**Comment by akutz** [comment]
Hi @vladimirvivien,

The problem is what I said it was above - your `glide.lock` file is out of date. See this [line](https://travis-ci.org/emccode/libstorage/builds/153859988#L332) in the build log:

```bash
[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
```

Also note that your hashes in the `glide.lock` (76e031331e2babb894129d8b21dce88922301411 ) and `glide.yaml` (0a0847888970ea577a2b9c96fcd5463dffbf7717) files do not match.

image

Please attempt to build locally before submitting a change. If `make` was used locally it would have caused the `glide.lock` file to be updated properly.

**Comment by vladimirvivien** [comment]
@akutz 
I ended up doing a `glide update` then run `make` which updated the glide.lock file with the correct hash.  However, as you can see, the build is failing with the same glide error with the old hash value even though the glide.lock file has been updated.

**Comment by akutz** [comment]
Um, looks good to me :)

**Comment by akutz** [comment]
Let's get Chris to build with this and validate the changes and then we merge SIO and then this.

**Pull request closed without merging**
